apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-app-{{APP_ENV}}
  namespace: {{APP_ENV}}
  labels:
    app: bot-app-{{APP_ENV}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-app-{{APP_ENV}}
  template:
    metadata:
      labels:
        app: bot-app-{{APP_ENV}}
    spec:
      containers:
        - name: bot-app-{{APP_ENV}}
          image: {{BOT_IMAGE}}
          env:
            - name: ENV
              value: {{APP_ENV}}
